"use client"
import {FormEvent, useEffect, useState} from "react"
import {useParams, useRouter} from "next/navigation"
type Review={id:string;status:string;original_filename:string;mime_type:string;evidence_url?:string;extraction?:{vendor_name?:string;invoice_number?:string;gstin?:string;subtotal?:string;cgst?:string;sgst?:string;igst?:string;total_amount?:string;validation_report?:string}|null}
export default function ReviewPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [doc,setDoc]=useState<Review|null>(null); const [form,setForm]=useState<Record<string,string>>({}); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false)
 async function load(){const r=await fetch(`/api/review/${id}`);if(r.status===401){router.push("/login");return}if(!r.ok){setMessage("Document could not be loaded.");return}const d=await r.json();setDoc(d);setForm(Object.fromEntries(["vendor_name","invoice_number","gstin","subtotal","cgst","sgst","igst","total_amount"].map(k=>[k,d.extraction?.[k]||""])))}
 useEffect(()=>{load()},[id])
 async function csrf(){const r=await fetch("/api/auth/csrf");return r.ok?(await r.json()).token:""}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch(`/api/review/${id}`,{method:"PATCH",headers:{"content-type":"application/json","x-csrf-token":await csrf()},body:JSON.stringify(form)});const text=await r.text();let d:any={};try{d=text?JSON.parse(text):{}}catch{}setBusy(false);if(!r.ok){setMessage(d.error?.message||"Could not save corrections.");return}setMessage("Corrections saved.");load()}
 async function transition(action:string){setBusy(true);const body=action==="reject"?JSON.stringify({reason:prompt("Rejection reason")||""}):undefined;const r=await fetch(`/api/review/${id}/${action}`,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":await csrf()},body});setBusy(false);if(!r.ok){const d=await r.json().catch(()=>({}));setMessage(d.error?.message||"Action failed.");return}router.push("/")}
 if(!doc)return <div className="loading">{message||"Loading review…"}</div>
 const e=doc.extraction; return <div className="shell"><main className="workspace"><header><div><p className="eyebrow">DOCUMENT REVIEW</p><h1>{doc.original_filename}</h1><p className="muted">Status: {doc.status.replace("_"," ")}</p></div><button className="outline" onClick={()=>router.push("/")}>Back</button></header>{message&&<div className="notice">{message}</div>}<section className="review-grid"><div className="panel"><h3>Original evidence</h3>{doc.evidence_url&&(doc.mime_type==="application/pdf"?<iframe title="Evidence" src={doc.evidence_url} style={{width:"100%",height:620,border:0}}/>:<img src={doc.evidence_url} alt="Uploaded evidence" style={{maxWidth:"100%",maxHeight:620,objectFit:"contain"}}/>)}<a href={doc.evidence_url} target="_blank">Open evidence</a></div><div className="panel"><h3>Extracted GST fields</h3><form onSubmit={save}>{Object.entries(form).map(([key,value])=><label key={key} className="review-field">{key.replaceAll("_"," ")}<input value={value} onChange={x=>setForm({...form,[key]:x.target.value})}/></label>)}<button disabled={busy}>{busy?"Saving…":"Save corrections"}</button></form>{e?.validation_report&&<><h3 className="review-subhead">Validation report</h3><pre className="validation">{e.validation_report}</pre></>}<div className="review-actions"><button className="approve" disabled={busy} onClick={()=>transition("approve")}>Approve</button><button className="reject" disabled={busy} onClick={()=>transition("reject")}>Reject</button></div></div></section></main></div>
}
