"use client"
import { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'

type LineItem={item_name?:string|null;description?:string|null;quantity?:string|number|null;unit?:string|null;unit_price?:string|number|null;tax?:string|number|null;discount?:string|number|null;total?:string|number|null}
type Extraction={vendor_name?:string|null;invoice_number?:string|null;gstin?:string|null;subtotal?:string|null;cgst?:string|null;sgst?:string|null;igst?:string|null;total_amount?:string|null;validation_report?:string|null;line_items?:LineItem[]}
type Document={id:string;original_filename:string;mime_type:string;document_type:string;status:string;uploaded_at:string;processing_error?:string|null;extraction?:Extraction|null}
const money=(value?:string|number|null)=>value===null||value===undefined||value===''?'—':`₹${Number(value).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const label=(value:string)=>value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function DocumentDetail(){
  const params=useParams<{id:string}>(), router=useRouter(), id=Array.isArray(params.id)?params.id[0]:params.id
  const [document,setDocument]=useState<Document|null>(null), [error,setError]=useState(''), [loading,setLoading]=useState(true)
  useEffect(()=>{if(!id)return;let active=true;fetch(`/api/documents/${id}`).then(async response=>{if(!response.ok)throw new Error(response.status===404?'This document no longer exists or is not available for this client.':'Document could not be loaded. Please try again.');return response.json()}).then(data=>{if(active)setDocument(data)}).catch(err=>{if(active)setError(err.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id])
  const validation=useMemo(()=>{try{return document?.extraction?.validation_report?JSON.parse(document.extraction.validation_report):null}catch{return null}},[document])
  if(loading)return <main className="document-detail-state">Loading document…</main>
  if(error)return <main className="document-detail-state"><h1>Document could not be loaded</h1><p>{error}</p><button onClick={()=>router.push('/')}>Back to documents</button></main>
  if(!document)return null
  const e=document.extraction
  return <main className="document-detail"><header className="detail-header"><div><p>DOCUMENT REVIEW</p><h1>{document.original_filename}</h1><span className={`detail-status ${document.status}`}>{label(document.status)}</span></div><button className="detail-back" onClick={()=>router.push('/')}>← Back to documents</button></header><div className="detail-layout"><section className="detail-card evidence"><div className="detail-card-heading"><div><p>ORIGINAL EVIDENCE</p><h2>Bill image</h2></div><a href={`/api/documents/${document.id}/file`} target="_blank" rel="noreferrer">Open full size ↗</a></div><div className="evidence-frame">{document.mime_type==='application/pdf'?<iframe src={`/api/documents/${document.id}/file`} title={document.original_filename}/>:<img src={`/api/documents/${document.id}/file`} alt={document.original_filename}/>}</div></section><section className="detail-main"><section className="detail-card"><div className="detail-card-heading"><div><p>EXTRACTED INFORMATION</p><h2>Bill details</h2></div>{!e&&<span className="detail-muted">Not extracted yet</span>}</div>{e?<><div className="field-grid"><Field label="Vendor name" value={e.vendor_name}/><Field label="Invoice number" value={e.invoice_number}/><Field label="GSTIN" value={e.gstin}/><Field label="Document type" value={label(document.document_type)}/></div><div className="amount-grid"><Amount label="Subtotal" value={e.subtotal}/><Amount label="CGST" value={e.cgst}/><Amount label="SGST" value={e.sgst}/><Amount label="IGST" value={e.igst}/><Amount label="Total amount" value={e.total_amount} total/></div></>:<p className="detail-muted">No extracted details are available for this bill yet.</p>}</section>{e?.line_items?.length?<section className="detail-card"><div className="detail-card-heading"><div><p>LINE ITEMS</p><h2>Extracted items</h2></div></div><div className="item-list">{e.line_items.map((item,index)=><div className="item-row" key={index}><div><strong>{item.item_name||item.description||`Item ${index+1}`}</strong><small>{item.quantity||'—'} {item.unit||''} × {money(item.unit_price)}</small></div><strong>{money(item.total)}</strong></div>)}</div></section>:null}{validation?.errors?.length?<section className="detail-card validation"><div className="detail-card-heading"><div><p>VALIDATION</p><h2>{validation.errors.length} item{validation.errors.length===1?'':'s'} need attention</h2></div></div>{validation.errors.map((issue:{field:string;message:string},index:number)=><div className="validation-row" key={index}><strong>{label(issue.field)}</strong><span>{issue.message}</span></div>)}</section>:null}</section></div></main>
}
function Field({label,value}:{label:string;value?:string|null}){return <div className="detail-field"><span>{label}</span><strong>{value||'—'}</strong></div>}
function Amount({label,value,total}:{label:string;value?:string|null;total?:boolean}){return <div className={`amount ${total?'total':''}`}><span>{label}</span><strong>{money(value)}</strong></div>}
