steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/finance/bills-voucher-web:$COMMIT_SHA", "frontend"]
images: ["${_REGION}-docker.pkg.dev/$PROJECT_ID/finance/bills-voucher-web:$COMMIT_SHA"]
substitutions: { _REGION: asia-south1 }
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
