steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/finance/bills-voucher:$COMMIT_SHA", "."]
images: ["${_REGION}-docker.pkg.dev/$PROJECT_ID/finance/bills-voucher:$COMMIT_SHA"]
substitutions: { _REGION: asia-south1 }
