steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/aidirac-503309/finance/bills-voucher-web:${_TAG}', 'frontend']
images: ['asia-south1-docker.pkg.dev/aidirac-503309/finance/bills-voucher-web:${_TAG}']
substitutions:
  _TAG: v5-preview-20260924-r4
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
