export const GST_MODULE_NAME = process.env.NEXT_PUBLIC_GST_MODULE_NAME ?? 'GST Easy'
export const GST = {
  name: GST_MODULE_NAME, bills: 'Bills', returns: 'Returns & Credit', overview: 'Overview',
  tagline: 'Your evidence, connected.', process: 'Upload · Review · File',
  uploaded: 'Your uploaded bills', view: 'View: Monthly return prep',
  workingPapers: 'Download CA working papers', help: 'Understand these terms', learn: 'Learn more', close: 'Close',
  credit: 'Usable Input Tax Credit', liability: 'GST Liability on Sales', cash: 'Estimated GST Cash Requirement',
  nonGst: 'Purchases Without ITC', creditCaption: 'Eligible ITC · GSTR-3B 4(A)',
  creditDetail: 'After eligibility and matching adjustments', liabilityDetail: 'Includes e-commerce (ECO) liability payable in cash',
  cashDetail: 'After IGST / CGST / SGST set-off', nonGstDetail: 'Non-GST, exempt or non-creditable purchases',
  compare: 'How ITC Affects Your GST Payment', recorded: 'As recorded in your bills', matched: 'After GSTR-2B Matching',
  eligible: 'After ITC Eligibility Checks', noCredit: 'If No ITC Can Be Used',
  pendingGstin: 'GSTIN not yet added', addGstin: 'Add your GSTIN to unlock validation and export',
  empty: 'Upload purchase bills to see your confirmed GST figures.', uploadFirst: 'Upload your first bills',
  upload: 'Upload bills', drop: 'Drop your purchase bills here — PDF, photo, Excel or CSV',
  template: 'Download the Excel template', reading: 'Reading bill…', ready: 'Ready to review', attention: 'Needs your attention',
  supplier: 'Supplier', invoiceNo: 'Invoice no', date: 'Date', taxable: 'Taxable value', tax: 'GST', total: 'Total',
  itc: 'ITC status', actions: 'Actions', review: 'Review', confirm: 'Confirm bill', reject: 'Reject',
  export: 'Export purchase register', original: 'Original bill', invoice: 'GST invoice', details: 'Bill details',
  save: 'Save changes', saved: 'Bill updated. Checks have been refreshed.', back: 'Back to bills',
  failed: 'The action could not be completed. Please try again.', all: 'All bills', filter: 'Bill status',
  loading: 'Loading bills', none: 'No bills for this period yet.', readOnly: 'You can view bills and export the confirmed purchase register.',
  recipient: 'Recipient', lineItems: 'Line items', addLine: 'Add line', remove: 'Remove line',
  sectionHeads: 'Credit and liability by tax head', head: 'Tax head', creditShort: 'Usable credit', cashShort: 'Cash requirement',
  formula: 'GST Liability on Sales − Usable ITC = Estimated Cash Requirement',
  formulaNote: 'Indicative only. Tax-head restrictions, opening balances, interest, late fees and your final return can change the cash requirement.',
  illustration: 'Matching illustration — example amounts only', appears: 'Appears in GSTR-2B', usable: 'Currently usable',
  yes: 'Yes', no: 'No', matchingPending: 'Import and review GSTR-2B in Returns & Credit to complete matching.',
  noMatching: 'Not yet matched', confirmNote: 'Confirm only after reviewing the original bill and all extracted details.',
  inputHint: 'Amounts are in rupees. Enter decimal values; changes are checked when you leave a field.',
  billOfSupply: 'Bill of supply', taxInvoice: 'Tax invoice', debitNote: 'Debit note', creditNote: 'Credit note',
  purchase: 'Purchase', sale: 'Sale', reverseCharge: 'Reverse charge', direction: 'Purchase or sale', type: 'Invoice type',
  originalDownload: 'Open original bill', maxFiles: 'Choose up to 20 files, each no larger than 15 MB.',
  status: {extracted:'Ready to review', needs_review:'Needs your attention', confirmed:'Confirmed', rejected:'Rejected',
    eligible:'Eligible', blocked_17_5:'Not creditable', ineligible_non_gst:'No GST credit', pending_review:'Needs review'} as Record<string,string>,
  fields: {supplier_gstin:'Supplier GSTIN',supplier_legal_name:'Supplier legal name',supplier_address:'Supplier address',
    recipient_gstin:'Recipient GSTIN',recipient_legal_name:'Recipient legal name',recipient_address:'Recipient address',
    invoice_number:'Invoice number',invoice_date:'Invoice date',place_of_supply_state_code:'Place of supply (state code)',
    description:'Description',hsn_sac:'HSN/SAC',quantity:'Quantity',unit:'Unit',taxable_value:'Taxable value',gst_rate:'GST rate %',
    cgst:'CGST',sgst:'SGST',igst:'IGST',cess:'Cess',invoice_total:'Invoice total'} as Record<string,string>,
  reasons: {client_gstin_missing:'Add your business GSTIN in Client profile before confirming this bill.',
    recipient_gstin_mismatch:'The recipient GSTIN does not match your business.',supplier_gstin_mismatch:'The supplier GSTIN does not match your business.',
    supplier_gstin_invalid:'Check the supplier GSTIN, including its last character.',recipient_gstin_invalid:'Check the recipient GSTIN.',
    place_of_supply_invalid:'Choose a valid place-of-supply state code.',invoice_identity_missing:'Enter the invoice date and a valid invoice number.',
    invoice_details_missing:'Complete the supplier name and bill line items.',hsn_invalid:'Check HSN/SAC: goods use 4, 6 or 8 digits; services use 6 digits beginning 99.',
    rate_invalid:'Choose a supported GST rate.',negative_amount:'Enter positive amounts; choose Credit note for a reduction.',
    tax_head_mismatch:'Check CGST and SGST for same-state supplies, or IGST for interstate supplies.',
    tax_arithmetic:'The GST on this bill does not match the taxable value and rate. Please check the tax amounts.',
    totals_mismatch:'The line amounts do not add up to the bill totals.',invoice_total_mismatch:'The total must equal taxable value plus taxes and cess.',
    low_confidence:'Check the extracted details against the original before confirming.',duplicate_invoice:'This supplier invoice already exists for the financial year.',
    reverse_charge_review:'Reverse-charge payment needs accountant review before credit can be confirmed.'} as Record<string,string>,
}
export const TOOLTIPS: Record<string,string> = {
  credit: 'GST you already paid on eligible business purchases can reduce what you pay in cash. Check supplier matching before claiming it.',
  liability: 'GST due on your taxable sales, not the sales value itself.',
  cash: 'Liability minus usable credit, subject to tax-head set-off. Opening balances, interest, late fees and final GSTR-3B can change it.',
  nonGst: 'Bills where GST is not charged, is exempt, or is classified as non-creditable.',
  recorded: 'The tax position based on the bills recorded for this period, before matching and eligibility adjustments.',
  matched: 'Only credit that also appears in your GSTR-2B counts as currently usable. An unmatched bill may become available in a later period.',
  eligible: 'Review duplicates, blocked items under Section 17(5), and the correct tax heads before claiming credit.',
  noCredit: 'The worst-case cash requirement: the full sales liability is paid without using input credit.',
}
export function monthName(period: string){return new Date(`${period}-01T12:00:00Z`).toLocaleDateString('en-IN',{month:'long',year:'numeric',timeZone:'UTC'})}
export function periodSummary(period:string, confirmed:number, review:number){return `${monthName(period)} · ${confirmed || review ? `${confirmed} bills confirmed, ${review} need review` : 'not yet calculated'}`}
