import {GST} from '../lib/copy/gst'
import Link from 'next/link'
import {Comparison,Delta} from './v7-panels'

export default function CustomerDashboard({data,money}:{data:any;money:(value:unknown)=>string}) {
  const summary=data.summary,totals=data.totals,period=data.period
  const filingHref=`/gst/workspace?period=${period}`
  return <>
    <section className="metric-grid overview-kpis">{[[GST.credit,totals?.eligible_credit,GST.creditDetail,'green'],[GST.liability,totals?.output_tax,GST.liabilityDetail,'blue'],[GST.cash,totals?.cash_required,GST.cashDetail,'amber'],[GST.nonGst,summary?.non_gst,'Excluded from input credit','green']].map(([label,value,detail,tone])=><div className={`metric-card ${tone}`} key={label}><span>{label}</span><strong>{summary&&totals?money(value):'—'}</strong><Delta value={data.deltas?.[String(label)]} period={period} sample={data.sample}/><small>{summary&&totals?detail:`No documents for ${period}`}</small></div>)}</section>
    {!summary||!totals?<><section className="bv-card empty-state"><h2>Your dashboard is ready for data</h2><p>No validated figures exist for this period yet. Upload your first bill or open the GST workspace to review documents.</p><Link className="button primary" href={`/documents?period=${period}`}>Upload your first bill</Link></section><div className="filing-grid"><section className="bv-card"><h2>Tax position</h2><p className="muted">Credit and liability by tax head will appear after validation.</p><div className="chart-placeholder" aria-label="Tax position chart placeholder">No validated financial entries</div></section><section className="bv-card"><h2>Reconciliation</h2><p className="muted">Match status will appear after GSTR-2B import.</p><div className="chart-placeholder" aria-label="Reconciliation chart placeholder">No GSTR-2B records</div></section></div></>:<>
      <Comparison summary={summary} money={money}/><div className="filing-grid"><section className="bv-card"><h2>Your tax position</h2><p className="muted">Credit and liability by tax head, using 49A/49B set-off.</p><div className="table-scroll"><table><thead><tr><th>Tax head</th><th>Eligible credit</th><th>{GST.liability}</th><th>ECO liability</th><th>Cash required</th></tr></thead><tbody>{['igst','cgst','sgst','cess'].map(h=><tr key={h}><td className="uppercase">{h}</td>{['eligible_by_head','output_by_head','eco_by_head','cash_by_head'].map(k=><td className="money" key={k}>{money(summary[k]?.[h]||'0')}</td>)}</tr>)}</tbody></table></div></section>
      <section className="bv-card"><h2>Credit adjustments</h2><p className="muted">Amounts excluded from currently eligible credit.</p><div className="recon-list">{[['blocked','Blocked credit'],['deferred','Deferred credit'],['reversal','Credit reversals']].map(([key,label])=><div key={key}><span>{label}</span><strong>{money(totals[key])}</strong></div>)}<div><span>{GST.nonGst}</span><strong>{money(summary.non_gst||'0')}</strong></div></div><Link href={filingHref}>View credit decisions →</Link></section></div>
    </>}
  </>
}
