'use client'
import {useState} from 'react'
import CustomerDashboard from './customer-dashboard'
import AssistantPanel from './assistant-panel'
import EvidenceSearch from './evidence-search'

export default function DemoLab({initial,initialTab,money}:{initial:any;initialTab?:string;money:(value:unknown)=>string}){
 const [bundle,setBundle]=useState(initial),[tab,setTab]=useState(initialTab&&['dashboard','documents','filing','search','assistant'].includes(initialTab)?initialTab:'dashboard'),[selected,setSelected]=useState<any>(null),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const options=initial.scenario_options||initial.coverage.map((id:string)=>({id,label:id.replaceAll('_',' ')}))
 async function choose(scenario:string){setBusy(true);setError('');try{const query=new URLSearchParams({scenario,period:bundle.period,seed:String(bundle.seed)});const r=await fetch('/api/demo/data?'+query);const d=await r.json();if(!r.ok)throw Error(d.error?.message||'Demo data could not be loaded.');setBundle(d);setSelected(null);setPage(0)}catch(e){setError(e instanceof Error?e.message:'Please retry.')}finally{setBusy(false)}}
 function download(){const payload={...bundle};delete payload.user;delete payload.scenario_options;const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`MOCK-${bundle.scenario}-${bundle.period}.json`;a.click();URL.revokeObjectURL(url)}
 const docs=bundle.documents||[],ledger=bundle.ledger||[]
 return <><div className="demo-notice"><strong>Demo workspace · Synthetic data</strong><p>Explore example customer records. These figures are separate from your live account, and cannot be filed or saved to it.</p></div><section className="bv-card demo-controls"><label>Example scenario<select aria-label="Demo scenario" value={bundle.scenario} disabled={busy} onChange={e=>choose(e.target.value)}>{options.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><div><p>{bundle.description}</p><small className="muted">{docs.length} example documents · Period {bundle.period} · Repeatable seed {bundle.seed}</small></div><button className="button secondary" onClick={download}>Download mock JSON</button></section>
 {error&&<p className="notice" role="alert">{error}</p>}{busy&&<p role="status">Loading scenario…</p>}<div className="demo-tabs" role="tablist" aria-label="Demo views">{['dashboard','documents','filing','search','assistant'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={`button ${tab===t?'primary':'secondary'}`} onClick={()=>{setTab(t);setSelected(null)}}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
 <div role="tabpanel">{tab==='dashboard'&&<CustomerDashboard data={bundle.dashboard} money={money}/>}
 {tab==='documents'&&<><section className="metric-grid">{['validated','needs_review','failed'].map(state=><div className="metric-card" key={state}><span>{state.replaceAll('_',' ')}</span><strong>{docs.filter((d:any)=>d.silver?.validation_status===state).length}</strong></div>)}</section><section className="bv-card"><h2>Example documents</h2>{docs.length?<><div className="table-scroll"><table><thead><tr><th>Invoice</th><th>Supplier</th><th>Total</th><th>Stage</th><th>Status</th><th/></tr></thead><tbody>{docs.slice(page*20,page*20+20).map((d:any)=><tr key={d.doc_id}><td>{d.silver?.invoice_no}<small>{d.original_filename}</small></td><td>{d.silver?.supplier_name}</td><td className="money">{money(d.silver?.total)}</td><td>{d.stage}</td><td>{d.silver?.validation_status.replaceAll('_',' ')}</td><td><button className="button quiet" onClick={()=>setSelected(d)}>View</button></td></tr>)}</tbody></table></div><div className="pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={(page+1)*20>=docs.length} onClick={()=>setPage(page+1)}>Next</button></div></>:<p className="empty-state">This example period has no documents.</p>}</section></>}
 {tab==='filing'&&<><section className="bv-card"><div className="section-heading"><h2>Credit decisions</h2><span className="chip">{bundle.dashboard.filing.state}</span></div><p className="muted">Example workflow only. Filing and record changes are disabled.</p>{ledger.length?<div className="table-scroll"><table><thead><tr><th>Invoice</th><th>Description</th><th>Decision</th><th>Rule</th></tr></thead><tbody>{ledger.map((r:any)=><tr key={r.doc_id}><td>{r.invoice_no}</td><td>{r.description}</td><td>{r.reason_code}</td><td>{r.rule_ref}</td></tr>)}</tbody></table></div>:<p className="empty-state">No validated ledger entries in this scenario.</p>}</section><section className="bv-card"><h2>GSTR-2B reconciliation</h2><div className="recon-list">{['matched','unmatched_books','unmatched_2b','amount_mismatch'].map(s=><div key={s}><span>{s.replaceAll('_',' ')}</span><strong>{bundle.matches.filter((m:any)=>m.match_status===s).length}</strong></div>)}</div></section></>}
 {tab==='search'&&<EvidenceSearch key={bundle.scenario} period={bundle.period} scenario={bundle.scenario} onSelect={setSelected} money={money}/>}
 {tab==='assistant'&&<AssistantPanel key={bundle.scenario} period={bundle.period} scenario={bundle.scenario}/>}
 {selected&&<section className="bv-card" aria-label="Synthetic invoice details"><div className="section-heading"><h2>{selected.silver.invoice_no} · Synthetic invoice</h2><button className="button quiet" onClick={()=>setSelected(null)}>Close details</button></div><p>{selected.silver.supplier_name} · {selected.silver.invoice_date}</p><p>Total: <strong>{money(selected.silver.total)}</strong> · {selected.silver.validation_status.replaceAll('_',' ')}</p><p>{selected.search_text}</p>{selected.silver.validation_errors?.length>0&&<p className="notice">{selected.silver.validation_errors.join(' · ')}</p>}<div className="recon-list">{['taxable_value','igst','cgst','sgst','cess'].map(h=><div key={h}><span>{h.replaceAll('_',' ')}</span><strong>{money(selected.silver[h])}</strong></div>)}</div><p className="muted">Generated example; no original customer document is attached.</p></section>}
 </div></>
}
