'use client'
import {GST} from '../lib/copy/gst'

import Link from 'next/link'
import {useState} from 'react'
import {Comparison,Delta,sampleReason,EmptyState} from './v7-panels'

const heads=['igst','cgst','sgst','cess']
const sum=(values:any[])=>{const total=values.reduce((n:bigint,v:any)=>{const raw=String(v||'0');const [w,f='']=raw.replace('-','').split('.');const cents=BigInt(w)*BigInt(100)+BigInt(f.padEnd(2,'0').slice(0,2));return n+(raw.startsWith('-')?-cents:cents)},BigInt(0));const absolute=total<BigInt(0)?-total:total;return `${total<BigInt(0)?'-':''}${absolute/BigInt(100)}.${String(absolute%BigInt(100)).padStart(2,'0')}`}
export default function GstWorkspace({data,money}:{data:any;money:(n:any)=>string}){
 const [tab,setTab]=useState('Readiness'),[query,setQuery]=useState(''),[page,setPage]=useState(0)
 const checks=(data.checks||[]).filter((c:any)=>c.code!=='GSTIN_REQUIRED'),summary=data.summary,blockers=checks.filter((c:any)=>c.severity==='blocker')
 const tabs=['Readiness','Purchases','ITC decisions','Reconciliation','Sales','GSTR-2B','Downloads','Client profile']
 const params=new URLSearchParams({period:data.period,scope:data.scope})
 const rows:any[]=tab==='Purchases'?data.documents:tab==='ITC decisions'?data.ledger:tab==='Reconciliation'?data.matches:tab==='Sales'?data.outward:tab==='GSTR-2B'?data.gstr2b:[]
 const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),shown=filtered.slice(page*20,(page+1)*20)
 function choose(t:string){setTab(t);setQuery('');setPage(0)}
 return <div className="gst-workspace">
  <section className="bv-card gst-context"><div><span className="chip success">{data.sample?'Sample illustration':'Customer records'}</span><h2>{data.profile?.legal_name||'Client profile incomplete'}</h2><p className="muted">{data.period_label} · {data.sample?'Sample — ':''}{data.monthly.filter((m:any)=>m.summary).length} of {data.periods.length} months{data.sample?'':' computed'}</p></div><label>Reporting view<select aria-label="Reporting view" value={data.scope} onChange={e=>{window.location.href=`/gst/workspace?period=${data.period}&scope=${e.target.value}`}}><option value="month">Monthly preparation</option><option value="quarter">Quarterly review</option><option value="year">Financial-year review</option></select></label><span title={data.sample?sampleReason:undefined}>{data.sample?<button className="button primary" disabled>{GST.workingPapers}</button>:<a className="button primary" href={`/api/gst/workspace/download?${params}`}>{GST.workingPapers}</a>}</span></section>
  <section className="metric-grid">{[[GST.credit,summary?sum(heads.map(h=>summary.eligible_by_head[h])):null,'From checked purchases'],[GST.liability,summary?sum(heads.flatMap(h=>[summary.output_by_head[h],summary.eco_by_head[h]])):null,'Includes ECO liability'],[GST.cash,summary?.cash_required,'Opening balances and payments excluded'],[GST.nonGst,summary?.non_gst,'Excluded from input tax credit']].map(([label,value,note])=><div className="metric-card" key={label}><span>{label}</span><strong>{money(value)}</strong><Delta value={data.deltas?.[String(label)]} period={data.period} sample={data.sample}/><small>{note}</small></div>)}</section>
  {!summary&&<div className="notice">No validated financial figures are available for this reporting view. Actual uploaded records and their corrections are shown under Purchases.</div>}
  {summary&&!data.calculation_complete&&<div className="notice">Partial figures: some months have no completed calculation. This is not a complete return.</div>}
  {data.scope!=='month'&&<p className="notice">This view consolidates available monthly records. Cash estimates are added without credit carry-forward between months. Confirm QRMP eligibility and payments separately; financial-year review is not a GSTR-9 return.</p>}
  <nav className="gst-tabs" aria-label="GST workspace sections">{tabs.map(t=><button key={t} className={`button ${tab===t?'tab-active':'secondary'}`} aria-pressed={tab===t} onClick={()=>choose(t)}>{t}</button>)}</nav>
  {tab==='Readiness'&&<>{summary&&<Comparison summary={summary} money={money}/>}<section className="bv-card"><h2>Reconciliation</h2><div className="recon-list">{['matched','unmatched_books','amount_mismatch','unmatched_2b'].map(status=><div key={status}><span>{status.replaceAll('_',' ')}</span><strong>{data.matches.filter((r:any)=>r.match_status===status).length}</strong></div>)}</div></section><section className="bv-card"><div className="section-heading"><h2>What needs attention</h2><span className="chip warning">{blockers.length} checks to resolve</span></div><p className="muted">Review → reconcile → compute → prepare → file in the GST portal → record acknowledgement.</p><ul className="gst-checks">{checks.map((c:any,i:number)=><li key={i}><span className={`chip ${c.severity==='blocker'?'warning':''}`}>{c.period||'Workspace'}</span><div><strong>{c.severity==='blocker'?'Needs attention':'For your review'}</strong><p>{c.message}</p>{c.href&&<Link href={c.href}>Open correction →</Link>}</div></li>)}</ul></section><section className="bv-card"><h2>Period preparation</h2><div className="table-scroll"><table><thead><tr><th>Month</th><th>Purchases</th><th>To review</th><th>Sales</th><th>GSTR-2B</th><th>Calculation</th><th>Filing record</th><th/></tr></thead><tbody>{data.monthly.map((m:any)=><tr key={m.period}><td>{m.period}</td><td>{m.documents}</td><td>{m.review}</td><td>{m.outward_count}</td><td>{m.gstr2b_count}</td><td>{m.summary?'Computed':'Not computed'}</td><td>{m.filing.state.replaceAll('_',' ')}{m.filing.arn&&<small>ARN {m.filing.arn}</small>}</td><td><Link href={m.href}>Prepare month →</Link></td></tr>)}</tbody></table></div></section></>}
  {tab==='ITC decisions'&&<section className="bv-card"><h2>How your credit is determined</h2><p>Only reviewed purchases enter the calculation. Each invoice line is matched with GSTR-2B and assigned a rule reference. Credit follows 49A/49B tax-head set-off. Eligible credit is applied by tax head; blocked, deferred and reversed amounts are shown separately. Non-GST purchases do not create credit.</p>{summary&&<div className="table-scroll"><table><thead><tr><th>Tax head</th><th>Recorded</th><th>Eligible</th><th>Blocked</th><th>Deferred</th><th>Reversed</th><th>Output</th><th>ECO</th><th>{GST.cash}</th></tr></thead><tbody>{heads.map(h=><tr key={h}><td>{h.toUpperCase()}</td><td className="money">{money(summary.input_by_head[h])}</td><td className="money">{money(summary.eligible_by_head[h])}</td>{['blocked','deferred','reversal'].map(b=><td className="money" key={b}>{money(summary.credit_adjustments[b][h])}</td>)}<td className="money">{money(summary.output_by_head[h])}</td><td className="money">{money(summary.eco_by_head[h])}</td><td className="money">{money(summary.cash_by_head[h])}</td></tr>)}</tbody></table></div>}</section>}
  {['Purchases','ITC decisions','Reconciliation','Sales','GSTR-2B'].includes(tab)&&<section className="bv-card"><div className="section-heading"><h2>{tab}</h2><label className="gst-search">Search these records<input aria-label="Search workspace records" placeholder="Invoice, supplier, amount or rule" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label></div><p className="muted">{filtered.length} matching records · {data.period_label}</p>{tab==='Purchases'&&<p>Amounts below are extracted from source bills. A bill awaiting review contributes no validated credit.</p>}{shown.length?<div className="table-scroll"><table><thead><tr>{(tab==='Purchases'?['Source / invoice','Supplier','Extracted total','Review status','Corrections','Evidence']:tab==='ITC decisions'?['Invoice / line','Description','Decision','Rule','Eligible credit','Evidence']:tab==='Reconciliation'?['Invoice','Supplier GSTIN','Match','Difference','Evidence']:['Invoice / date',tab==='Sales'?'Recipient GSTIN':'Supplier GSTIN','Taxable value','IGST','CGST','SGST','Cess']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{shown.map((r:any,i:number)=><tr key={`${r.period}-${r.doc_id||r.invoice_no}-${r.line_no||i}`}>
   {tab==='Purchases'?<><td>{r.original_filename}<small>{r.silver?.invoice_no||'Invoice number pending'} · {r.period}</small></td><td>{r.silver?.supplier_name||'Awaiting extraction'}<small className="gstin-text">{r.silver?.supplier_gstin}</small></td><td className="money">{money(r.silver?.total)}</td><td>{r.silver?.validation_status==='validated'?'Checked':r.silver?.validation_status==='failed'?'Needs attention':r.silver?.validation_status?.replaceAll('_',' ')||'Landed'}</td><td>{r.issues.map((e:any)=><p key={e.code}>{e.message}</p>)}</td><td><Link href={r.review_url}>Review original →</Link></td></>:tab==='ITC decisions'?<><td>{r.invoice_no}<small>{r.period} · Line {r.line_no}</small></td><td>{r.description}</td><td>{r.reason_code}</td><td>{r.rule_ref}</td><td className="money">{money(sum(heads.map(h=>r[`eligible_${h}`])))}</td><td><Link href={`/documents/${r.doc_id}?period=${r.period}`}>View bill →</Link></td></>:tab==='Reconciliation'?<><td>{r.invoice_no}<small>{r.period}</small></td><td>{r.supplier_gstin}</td><td>{r.match_status?.replaceAll('_',' ')}</td><td className="money">{money(r.delta)}</td><td>{r.doc_id&&<Link href={`/documents/${r.doc_id}?period=${r.period}`}>View bill →</Link>}</td></>:<><td>{r.invoice_no}<small>{r.invoice_date} · {r.period}</small></td><td>{r.recipient_gstin||r.supplier_gstin||'Unregistered'}</td><td className="money">{money(r.taxable_value)}</td>{heads.map(h=><td className="money" key={h}>{money(r[h])}</td>)}</>}
  </tr>)}</tbody></table></div>:<EmptyState text={query?'No records match your search.':'No records for this period.'} href={`/documents?period=${data.period}`} label="Review documents"/>}<div className="pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(filtered.length/20))}</span><button disabled={(page+1)*20>=filtered.length} onClick={()=>setPage(page+1)}>Next</button></div><Link className="button secondary" href={`/gst/filing?period=${data.period}`}>Import records and compute ITC →</Link></section>}
  {tab==='Downloads'&&<section className="bv-card"><h2>Accountant working papers</h2><p>Download the selected customer's {data.period_label} records as a ZIP: purchase review, sales register, GSTR-2B register, ITC decisions, reconciliation, readiness checks and a complete JSON snapshot. The manifest records checksums for the files.</p><p className="notice">Preparation papers are not portal-upload JSON or proof of filing. Complete the checks, verify the final return in the GST portal and record its ARN after submission.</p><span title={data.sample?sampleReason:undefined}>{data.sample?<button className="button secondary" disabled>{GST.workingPapers}</button>:<a className="button secondary" href={`/api/gst/workspace/download?${params}`}>Download papers</a>}</span><p><Link href={`/gst/filing?period=${data.period}`}>Open monthly preparation and acknowledgement tracking →</Link></p></section>}
  {tab==='Client profile'&&<section className="bv-card"><h2>Client configuration</h2><dl className="gst-profile">{[['Legal name',data.profile?.legal_name],['GSTIN',data.profile?.gstin],['State',data.profile?.state_code],['Filing frequency',data.profile?.filing_frequency],['Business activity',data.profile?.business_nature]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</dl><p>The tax administrator must confirm the registration, filing frequency and applicable tax rules for each client. The account menu switches between clients you are authorised to access.</p></section>}
  <p className="muted"><Link href={`/search?period=${data.period}`}>Search source evidence</Link> · <Link href={`/assistant?period=${data.period}`}>Ask the assistant about this month</Link></p>
 </div>
}
